version: "3.8"

services:
  postgres:
    image: postgres:15.3
    container_name: data-engineering-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .. # Change to parent directory since dockerfile copies from root
      dockerfile: src/dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres # Match the postgres database name
      - POSTGRES_USER=postgres # Match the postgres user
      - POSTGRES_PASSWORD=postgres # Match the postgres password

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: data-engineering-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
